### ISSUE TITLE
file not found error

### ISSUE THREAD

**Issue by MV487** [Ajaykumar415/space-pew-pew-#2]
Traceback (most recent call last):
  File "c:\Users\User\Documents\GitHub\space-pew-pew-\main.py", line 11, in <module>
    icon = pygame.image.load('icon.png')

Traceback (most recent call last):
  File "c:\Users\User\Documents\GitHub\space-pew-pew-\main.py", line 42, in <module>
    font = pygame.font.Font('Bristone.ttf', 32)
FileNotFoundError: [Errno 2] No such file or directory: 'Bristone.ttf'

**Comment by MV487** [comment]
you should consider your file headers because it is different from the code.

**Comment by Ajaykumar415** [comment]
working on it.

**Comment by Ajaykumar415** [comment]
done!
